CREATE TABLE CW_PRIORITY (ID bigint, NAME varchar(50), PRIMARY KEY(ID, NAME));
CREATE TABLE CW_STATUS (ID bigint, NAME varchar(50), PRIMARY KEY(ID, NAME));
CREATE TABLE CW_ORGANIZATION_DETAILS(ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME Text, OWNERID bigint);
CREATE TABLE CW_TEAMSPACE_DETAILS(ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME Text, ORGANIZATIONID bigint, OWNERID, bigint, FOREIGN KEY(ORGANIZATIONID) REFERENCES CW_ORGANIZATION_DETAILS(ID));
CREATE TABLE CW_PROJECT_DETAILS (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME Text, STATUS bigint, PRIORITY bigint, TEAMSPACEID bigint, OWNERID bigint, FOREIGN KEY(STATUS) REFERENCES CW_STATUS(ID), FOREIGN KEY(PRIORITY) REFERENCES CW_PRIORITY(ID));
CREATE TABLE CW_TASK_DETAILS (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME Text, DESCRIPTION Text, STATUS bigint, PRIORITY bigint, PROJECTID bigint, OWNERID bigint, ASSIGNEEID bigint, PARENT_TASK_ID bigint, FOREIGN KEY(PROJECTID) REFERENCES CW_PROJECT_DETAILS(ID), FOREIGN KEY(STATUS) REFERENCES CW_STATUS(ID), FOREIGN KEY(PRIORITY) REFERENCES CW_PRIORITY(ID));

INSERT INTO CW_PRIORITY (ID, NAME) VALUES(1, 'Low');
INSERT INTO CW_PRIORITY (ID, NAME) VALUES(2, 'Medium');
INSERT INTO CW_PRIORITY (ID, NAME) VALUES(3, 'High');

INSERT INTO CW_STATUS (ID, NAME) VALUES(1, 'Planning');
INSERT INTO CW_STATUS (ID, NAME) VALUES(2, 'In Progress');
INSERT INTO CW_STATUS (ID, NAME) VALUES(3, 'Completed');