CREATE TABLE CW_PRIORITY (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME varchar(50));
CREATE TABLE CW_STATUS (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME varchar(50));
CREATE TABLE CW_ORGANIZATION_DETAILS(ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME Text, OWNERID bigint);
CREATE TABLE CW_TEAMSPACE(ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME Text, ORGANIZATIONID bigint, OWNERID, bigint, FOREIGN KEY(ORGANIZATIONID) REFERENCES CW_ORGANIZATION_DETAILS(ID));
CREATE TABLE CW_PROJECT_DETAILS (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME Text, STATUS bigint, PRIORITY bigint, TEAMSPACEID bigint, OWNERID bigint, FOREIGN KEY(STATUS) REFERENCES CW_STATUS(ID), FOREIGN KEY(PRIORITY) REFERENCES CW_PRIORITY(ID));
CREATE TABLE CW_TASK_DETAILS (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME Text, DESCRIPTION Text, STATUS bigint, PRIORITY bigint, PROJECTID bigint, OWNERID bigint, ASSIGNEEID bigint, PARENT_TASK_ID bigint, FOREIGN KEY(PROJECTID) REFERENCES CW_PROJECT_DETAILS(ID), FOREIGN KEY(STATUS) REFERENCES CW_STATUS(ID), FOREIGN KEY(PRIORITY) REFERENCES CW_PRIORITY(ID));

INSERT INTO CW_PRIORITY (NAME) VALUES('Low');
INSERT INTO CW_PRIORITY (NAME) VALUES('Medium');
INSERT INTO CW_PRIORITY (NAME) VALUES('High');

INSERT INTO CW_STATUS (NAME) VALUES('Planning');
INSERT INTO CW_STATUS (NAME) VALUES('In Progress');
INSERT INTO CW_STATUS (NAME) VALUES('Completed');